/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhungLearnSafe;

/**
 *
 * @author surface pro 6
 */
public class CertificateGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CertificateGUI.class.getName());
    private Account loggedInUser;
    private Quiz quiz;
    
    private void displayCert(){
        nameLBL.setText(loggedInUser.getUsername());
        quizLBL.setText(quiz.getTitle());
        
    }
    
    /**
     * Creates new form CertificateGUI
     * @param loggedInUser
     * @param quiz
     */
    public CertificateGUI(Account loggedInUser, Quiz quiz) {
        initComponents();
        this.loggedInUser = loggedInUser;
        this.quiz = quiz;
        displayCert();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLBL = new javax.swing.JLabel();
        quizLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(730, 520));
        setMinimumSize(new java.awt.Dimension(730, 520));
        getContentPane().setLayout(null);

        nameLBL.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        nameLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLBL.setText("[Name]");
        getContentPane().add(nameLBL);
        nameLBL.setBounds(137, 166, 430, 40);

        quizLBL.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        quizLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizLBL.setText("[Quiz title]");
        getContentPane().add(quizLBL);
        quizLBL.setBounds(150, 250, 410, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 694, 420);

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN);
        backBTN.setBounds(310, 440, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        new MainProgramGUI(loggedInUser, AccountManager.load()).setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Account loggedInUser = new Account();
        Quiz quiz = new Quiz() {
            @Override
            public void showLesson() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CertificateGUI(loggedInUser, quiz).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JLabel quizLBL;
    // End of variables declaration//GEN-END:variables
}
