/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhungLearnSafe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hong-nhung-nguyen
 */
public class FireQuizGUI extends javax.swing.JFrame implements Gradable{

    private boolean question1, question3;   //create flags for questions with checkboxes
    private Account loggedInUser;   //reference to logged in user
    private ArrayList<Account> users;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FireQuizGUI.class.getName());

    /**
     * Creates new form FireQuizGUI
     *
     * @param loggedInUser
     * @param users
     */
    public FireQuizGUI(Account loggedInUser, ArrayList<Account> users) {
        initComponents();
        this.loggedInUser = loggedInUser;
        this.users = users;
        AccountManager.load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q2BTNGR = new javax.swing.ButtonGroup();
        q4BTNGR = new javax.swing.ButtonGroup();
        q5BTNGR = new javax.swing.ButtonGroup();
        quitBTN = new javax.swing.JButton();
        submitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        question1PN = new javax.swing.JPanel();
        q1LBL = new javax.swing.JLabel();
        q1aCB = new javax.swing.JCheckBox();
        q1cCB = new javax.swing.JCheckBox();
        q1dCB = new javax.swing.JCheckBox();
        q1bCB = new javax.swing.JCheckBox();
        question2PN = new javax.swing.JPanel();
        q2LBL = new javax.swing.JLabel();
        q2aRBTN = new javax.swing.JRadioButton();
        q2bRBTN = new javax.swing.JRadioButton();
        q2cRBTN = new javax.swing.JRadioButton();
        question3PN = new javax.swing.JPanel();
        q3LBL = new javax.swing.JLabel();
        q3aCB = new javax.swing.JCheckBox();
        q3bCB = new javax.swing.JCheckBox();
        q3cCB = new javax.swing.JCheckBox();
        q3dCB = new javax.swing.JCheckBox();
        q3eCB = new javax.swing.JCheckBox();
        question4PN = new javax.swing.JPanel();
        q4LBL = new javax.swing.JLabel();
        q4aRBTN = new javax.swing.JRadioButton();
        q4bRBTN = new javax.swing.JRadioButton();
        q4cRBTN = new javax.swing.JRadioButton();
        question5PN = new javax.swing.JPanel();
        q5LBL = new javax.swing.JLabel();
        q5aRBTN = new javax.swing.JRadioButton();
        q5bRBTN = new javax.swing.JRadioButton();
        q5cRBTN = new javax.swing.JRadioButton();
        q5dRBTN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 710));
        setSize(new java.awt.Dimension(686, 710));

        quitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quitBTN.setText("Quit");
        quitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBTNActionPerformed(evt);
            }
        });

        submitBTN.setBackground(new java.awt.Color(255, 0, 0));
        submitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 255, 255));
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 750));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(808, 660));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(717, 821));

        jPanel2.setPreferredSize(new java.awt.Dimension(796, 991));

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(204, 0, 0));
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("FIRE SAFETY TRAINING");
        titleLBL.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titleLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        question1PN.setBackground(new java.awt.Color(255, 255, 153));

        q1LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q1LBL.setText("Question 1: What number(s) should you call when there is a fire?");

        q1aCB.setBackground(new java.awt.Color(255, 255, 153));
        q1aCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1aCB.setText("911");

        q1cCB.setBackground(new java.awt.Color(255, 255, 153));
        q1cCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1cCB.setText("123");

        q1dCB.setBackground(new java.awt.Color(255, 255, 153));
        q1dCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1dCB.setText("112");

        q1bCB.setBackground(new java.awt.Color(255, 255, 153));
        q1bCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1bCB.setText("999");
        q1bCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1bCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout question1PNLayout = new javax.swing.GroupLayout(question1PN);
        question1PN.setLayout(question1PNLayout);
        question1PNLayout.setHorizontalGroup(
            question1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question1PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(question1PNLayout.createSequentialGroup()
                        .addComponent(q1aCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q1bCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(q1cCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(q1dCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question1PNLayout.setVerticalGroup(
            question1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question1PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(question1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1aCB)
                    .addComponent(q1cCB)
                    .addComponent(q1dCB)
                    .addComponent(q1bCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        question2PN.setBackground(new java.awt.Color(255, 204, 102));

        q2LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q2LBL.setText("Question 2: What drill should you do when you or your child catches fire?");

        q2aRBTN.setBackground(new java.awt.Color(255, 204, 102));
        q2BTNGR.add(q2aRBTN);
        q2aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2aRBTN.setText("Stop, drop and roll");

        q2bRBTN.setBackground(new java.awt.Color(255, 204, 102));
        q2BTNGR.add(q2bRBTN);
        q2bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2bRBTN.setText("Livestream, cry and run");

        q2cRBTN.setBackground(new java.awt.Color(255, 204, 102));
        q2BTNGR.add(q2cRBTN);
        q2cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2cRBTN.setText("Continue, drop and crawl");

        javax.swing.GroupLayout question2PNLayout = new javax.swing.GroupLayout(question2PN);
        question2PN.setLayout(question2PNLayout);
        question2PNLayout.setHorizontalGroup(
            question2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question2PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q2LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(question2PNLayout.createSequentialGroup()
                        .addGroup(question2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2aRBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2bRBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2cRBTN))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question2PNLayout.setVerticalGroup(
            question2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question2PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2cRBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        question3PN.setBackground(new java.awt.Color(255, 153, 51));

        q3LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q3LBL.setText("Question 3: What actions should be included in your fire escape plan?");

        q3aCB.setBackground(new java.awt.Color(255, 153, 51));
        q3aCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3aCB.setText("Look for the cause of the fire");

        q3bCB.setBackground(new java.awt.Color(255, 153, 51));
        q3bCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3bCB.setText("Call 112 or 999");

        q3cCB.setBackground(new java.awt.Color(255, 153, 51));
        q3cCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3cCB.setText("Do not go back into your house until fire brigade says it is safe");

        q3dCB.setBackground(new java.awt.Color(255, 153, 51));
        q3dCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3dCB.setText("Open every door");

        q3eCB.setBackground(new java.awt.Color(255, 153, 51));
        q3eCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3eCB.setText("Meet at an assembly point outside your home");

        javax.swing.GroupLayout question3PNLayout = new javax.swing.GroupLayout(question3PN);
        question3PN.setLayout(question3PNLayout);
        question3PNLayout.setHorizontalGroup(
            question3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question3PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q3LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(question3PNLayout.createSequentialGroup()
                        .addGroup(question3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(q3eCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3dCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3aCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3bCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3cCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question3PNLayout.setVerticalGroup(
            question3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question3PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q3LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3aCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3bCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3cCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3dCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q3eCB)
                .addGap(112, 112, 112))
        );

        question4PN.setBackground(new java.awt.Color(255, 153, 153));

        q4LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q4LBL.setText("Question 4: What should you do with fire extinguishers and fire blanket?");

        q4aRBTN.setBackground(new java.awt.Color(255, 153, 153));
        q4BTNGR.add(q4aRBTN);
        q4aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4aRBTN.setText("Purchase a new one every year");
        q4aRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4aRBTNActionPerformed(evt);
            }
        });

        q4bRBTN.setBackground(new java.awt.Color(255, 153, 153));
        q4BTNGR.add(q4bRBTN);
        q4bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4bRBTN.setText("Learn how to use them and keep them at a place easy to get");

        q4cRBTN.setBackground(new java.awt.Color(255, 153, 153));
        q4BTNGR.add(q4cRBTN);
        q4cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4cRBTN.setText("Keep them in a safe to avoid burglars");

        javax.swing.GroupLayout question4PNLayout = new javax.swing.GroupLayout(question4PN);
        question4PN.setLayout(question4PNLayout);
        question4PNLayout.setHorizontalGroup(
            question4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question4PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(question4PNLayout.createSequentialGroup()
                        .addGroup(question4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(q4cRBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q4aRBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4bRBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question4PNLayout.setVerticalGroup(
            question4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question4PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q4LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4cRBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        question5PN.setBackground(new java.awt.Color(255, 102, 102));

        q5LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q5LBL.setText("Question 5: How do you protect children against fire?");

        q5aRBTN.setBackground(new java.awt.Color(255, 102, 102));
        q5BTNGR.add(q5aRBTN);
        q5aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5aRBTN.setText("Supervise children around fire hazards like oven, chip pan, heaters, etc");

        q5bRBTN.setBackground(new java.awt.Color(255, 102, 102));
        q5BTNGR.add(q5bRBTN);
        q5bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5bRBTN.setText("Do not expect children to look after themselves around fires");

        q5cRBTN.setBackground(new java.awt.Color(255, 102, 102));
        q5BTNGR.add(q5cRBTN);
        q5cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5cRBTN.setText("Cover stoves and heaters with a fireguard secured to the wall");

        q5dRBTN.setBackground(new java.awt.Color(255, 102, 102));
        q5BTNGR.add(q5dRBTN);
        q5dRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5dRBTN.setText("All of the above");

        javax.swing.GroupLayout question5PNLayout = new javax.swing.GroupLayout(question5PN);
        question5PN.setLayout(question5PNLayout);
        question5PNLayout.setHorizontalGroup(
            question5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question5PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q5LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(question5PNLayout.createSequentialGroup()
                        .addGroup(question5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q5dRBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5aRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5bRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5cRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question5PNLayout.setVerticalGroup(
            question5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question5PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q5LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5cRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5dRBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(question4PN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question3PN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question2PN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question1PN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question5PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question1PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question2PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question3PN, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question4PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question5PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(quitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBTN)
                    .addComponent(quitBTN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // Calculate grades
        grade();

        // update user's fire score
        loggedInUser.setFireScore(Integer.toString(fireScore));
        
        // reading data from file to array list
        users = AccountManager.load();

        //update in the array list by replacing old account with updated account
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUsername().equals(loggedInUser.getUsername())) {
                users.set(i, loggedInUser); // replace with updated account
                break;
            }
        }

        // Write array list back to file
        AccountManager.writeToFile(users);

        // Display test score when going back to main program
        MainProgramGUI m = new MainProgramGUI(loggedInUser, users);
        m.displayFireScore();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_submitBTNActionPerformed

    private void quitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBTNActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit? You will lose all your progress.", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new MainProgramGUI(loggedInUser, users).setVisible(true);
            dispose();
            // If NO, do nothing
        }
    }//GEN-LAST:event_quitBTNActionPerformed

    private void q4aRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4aRBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4aRBTNActionPerformed

    private void q1bCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1bCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1bCBActionPerformed

    private int fireScore = 0;
    @Override
    public void grade() {
        //Question 1
        question1 = false;
        if (q1bCB.isSelected() && q1dCB.isSelected()) {    //Correct answers are B and D
            question1 = true;
        }
        if (q1aCB.isSelected() || q1cCB.isSelected()) {
            question1 = false;
        }
        if (question1 == true) {
            fireScore++;
        }

        //Question 2: Correct answer is A
        if (q2aRBTN.isSelected()) {
            fireScore++;
        }

        //Question 3: Correct answers are B, C, and E
        question3 = false;
        if (q3bCB.isSelected() & q3cCB.isSelected() & q3eCB.isSelected()) {
            question3 = true;
        }
        if (q3aCB.isSelected() || q3dCB.isSelected()) {
            question3 = false;
        }
        if (question3 == true) {
            fireScore++;
        }

        //Question 4: Correct answer is B
        if (q4bRBTN.isSelected()) {
            fireScore++;
        }

        //Question 5: Correct answer is D
        if (q5dRBTN.isSelected()) {
            fireScore++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Account a = new Account();
        ArrayList<Account> users = new ArrayList<>();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FireQuizGUI(a, users).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel q1LBL;
    private javax.swing.JCheckBox q1aCB;
    private javax.swing.JCheckBox q1bCB;
    private javax.swing.JCheckBox q1cCB;
    private javax.swing.JCheckBox q1dCB;
    private javax.swing.ButtonGroup q2BTNGR;
    private javax.swing.JLabel q2LBL;
    private javax.swing.JRadioButton q2aRBTN;
    private javax.swing.JRadioButton q2bRBTN;
    private javax.swing.JRadioButton q2cRBTN;
    private javax.swing.JLabel q3LBL;
    private javax.swing.JCheckBox q3aCB;
    private javax.swing.JCheckBox q3bCB;
    private javax.swing.JCheckBox q3cCB;
    private javax.swing.JCheckBox q3dCB;
    private javax.swing.JCheckBox q3eCB;
    private javax.swing.ButtonGroup q4BTNGR;
    private javax.swing.JLabel q4LBL;
    private javax.swing.JRadioButton q4aRBTN;
    private javax.swing.JRadioButton q4bRBTN;
    private javax.swing.JRadioButton q4cRBTN;
    private javax.swing.ButtonGroup q5BTNGR;
    private javax.swing.JLabel q5LBL;
    private javax.swing.JRadioButton q5aRBTN;
    private javax.swing.JRadioButton q5bRBTN;
    private javax.swing.JRadioButton q5cRBTN;
    private javax.swing.JRadioButton q5dRBTN;
    private javax.swing.JPanel question1PN;
    private javax.swing.JPanel question2PN;
    private javax.swing.JPanel question3PN;
    private javax.swing.JPanel question4PN;
    private javax.swing.JPanel question5PN;
    private javax.swing.JButton quitBTN;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
