/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhungLearnSafe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hong-nhung-nguyen
 */
public class FloodQuizGUI extends javax.swing.JFrame implements Gradable{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FloodQuizGUI.class.getName());

    private Account loggedInUser;   //reference to logged in user
    private ArrayList<Account> users;
    
    /**
     * Creates new form FloodQuizGUI
     * @param loggedInUser
     * @param users
     */
    public FloodQuizGUI(Account loggedInUser, ArrayList<Account> users) {
        initComponents();
        this.loggedInUser = loggedInUser;
        this.users = users;
        AccountManager.load();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupQ1 = new javax.swing.ButtonGroup();
        buttonGroupQ4 = new javax.swing.ButtonGroup();
        buttonGroupQ5 = new javax.swing.ButtonGroup();
        submitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        q1PN = new javax.swing.JPanel();
        q1LBL = new javax.swing.JLabel();
        q1aRBTN = new javax.swing.JRadioButton();
        q1bRBTN = new javax.swing.JRadioButton();
        q1cRBTN = new javax.swing.JRadioButton();
        q2PN = new javax.swing.JPanel();
        q2LBL = new javax.swing.JLabel();
        q2aCB = new javax.swing.JCheckBox();
        q2bCB = new javax.swing.JCheckBox();
        q3PN = new javax.swing.JPanel();
        q3LBL = new javax.swing.JLabel();
        q3aCB = new javax.swing.JCheckBox();
        q3bCB = new javax.swing.JCheckBox();
        q3cCB = new javax.swing.JCheckBox();
        q3dCB = new javax.swing.JCheckBox();
        q3eCB = new javax.swing.JCheckBox();
        q3fCB = new javax.swing.JCheckBox();
        q4PN = new javax.swing.JPanel();
        q4LBL = new javax.swing.JLabel();
        q4aRBTN = new javax.swing.JRadioButton();
        q4bRBTN = new javax.swing.JRadioButton();
        q4cRBTN = new javax.swing.JRadioButton();
        q5PN = new javax.swing.JPanel();
        q5LBL = new javax.swing.JLabel();
        q5aRBTN = new javax.swing.JRadioButton();
        q5bRBTN = new javax.swing.JRadioButton();
        q5cRBTN = new javax.swing.JRadioButton();
        quitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitBTN.setBackground(new java.awt.Color(51, 102, 255));
        submitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 255, 255));
        submitBTN.setText("SUBMIT");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        titleLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 102, 204));
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("FLOOD SAFETY TRAINING");

        q1LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q1LBL.setText("Question 1: Which option is a part of preparing for a potential flood?");

        buttonGroupQ1.add(q1aRBTN);
        q1aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1aRBTN.setText("Write a will no matter how young you are");

        buttonGroupQ1.add(q1bRBTN);
        q1bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1bRBTN.setText("Write an essay on the danger of flood");

        buttonGroupQ1.add(q1cRBTN);
        q1cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1cRBTN.setText("Write a list of your most valuable possessions and where they are stored.");

        javax.swing.GroupLayout q1PNLayout = new javax.swing.GroupLayout(q1PN);
        q1PN.setLayout(q1PNLayout);
        q1PNLayout.setHorizontalGroup(
            q1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(q1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(q1PNLayout.createSequentialGroup()
                        .addGroup(q1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q1aRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q1bRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q1cRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q1PNLayout.setVerticalGroup(
            q1PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q1aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q1bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q1cRBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        q2LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q2LBL.setText("Question 2: Choose the appropriate extra preparation steps for the elderly");

        q2aCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2aCB.setText("Plan an evacuation route and destination");

        q2bCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2bCB.setText("Keep an up to date list of important and useful contact numbers");

        javax.swing.GroupLayout q2PNLayout = new javax.swing.GroupLayout(q2PN);
        q2PN.setLayout(q2PNLayout);
        q2PNLayout.setHorizontalGroup(
            q2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(q2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(q2bCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q2aCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(q2LBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        q2PNLayout.setVerticalGroup(
            q2PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q2LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2aCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2bCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        q3LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q3LBL.setText("Question 3: What are potential health risks associated with flooding?");

        q3aCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3aCB.setText("Burn");

        q3bCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3bCB.setText("Carbon Monoxide Poisoning");

        q3cCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3cCB.setText("Biological Contamination");

        q3dCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3dCB.setText("Blindness");

        q3eCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3eCB.setText("Electrical Hazards");

        q3fCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3fCB.setText("Bankruptcy");

        javax.swing.GroupLayout q3PNLayout = new javax.swing.GroupLayout(q3PN);
        q3PN.setLayout(q3PNLayout);
        q3PNLayout.setHorizontalGroup(
            q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q3LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(q3PNLayout.createSequentialGroup()
                        .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(q3cCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3bCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3aCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q3dCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3eCB, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(q3fCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q3PNLayout.setVerticalGroup(
            q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3PNLayout.createSequentialGroup()
                .addComponent(q3LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3aCB)
                    .addComponent(q3dCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3bCB)
                    .addComponent(q3eCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(q3PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3cCB)
                    .addComponent(q3fCB))
                .addContainerGap())
        );

        q4LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q4LBL.setText("Question 4: How do you protect your health against drowning and injury?");

        buttonGroupQ4.add(q4aRBTN);
        q4aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4aRBTN.setText("Wear appropriate clothing/footwear and stay visible");

        buttonGroupQ4.add(q4bRBTN);
        q4bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4bRBTN.setText("Follow the survival tips of TikTok influencers");

        buttonGroupQ4.add(q4cRBTN);
        q4cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4cRBTN.setText("Stay indoor at all time");

        javax.swing.GroupLayout q4PNLayout = new javax.swing.GroupLayout(q4PN);
        q4PN.setLayout(q4PNLayout);
        q4PNLayout.setHorizontalGroup(
            q4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4PNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(q4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(q4PNLayout.createSequentialGroup()
                        .addGroup(q4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q4aRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q4bRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q4cRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q4PNLayout.setVerticalGroup(
            q4PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q4LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q4cRBTN)
                .addGap(112, 112, 112))
        );

        q5LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q5LBL.setText("Question 5: How do you minimize biological contamination?");

        buttonGroupQ5.add(q5aRBTN);
        q5aRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5aRBTN.setText("Buy all fresh food from the supermarket one week before the flood");

        buttonGroupQ5.add(q5bRBTN);
        q5bRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5bRBTN.setText("Avoid contact with contaminated water");

        buttonGroupQ5.add(q5cRBTN);
        q5cRBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q5cRBTN.setText("Pray");

        javax.swing.GroupLayout q5PNLayout = new javax.swing.GroupLayout(q5PN);
        q5PN.setLayout(q5PNLayout);
        q5PNLayout.setHorizontalGroup(
            q5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q5LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(q5PNLayout.createSequentialGroup()
                .addGroup(q5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(q5bRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q5aRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q5cRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        q5PNLayout.setVerticalGroup(
            q5PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q5LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5aRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5bRBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5cRBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q2PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(q4PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(q5PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q1PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4PN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        quitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quitBTN.setText("QUIT");
        quitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(quitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitBTN)
                    .addComponent(submitBTN))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int floodScore = 0;
    @Override
    public void grade() {
        //Question 1: Choose C
        if(q1cRBTN.isSelected()){
            floodScore++;
        } 
        
        //Question 2: Choose all options
        if (q2aCB.isSelected() & q2bCB.isSelected()) {
            floodScore++;
        }

        //Question 3: Choose B, C, E
        boolean question3 = false;
        if (q3bCB.isSelected() & q3cCB.isSelected() & q3eCB.isSelected()) {
            question3 = true;
        }
        if (q3aCB.isSelected() || q3dCB.isSelected() || q3fCB.isSelected()) {
            question3 = false;
        }
        if (question3 == true) {
            floodScore++;
        }

        //Question 4: Choose A
        if (q4aRBTN.isSelected()) {
            floodScore++;
        }

        //Question 5: Choose B
        if (q5bRBTN.isSelected()) {
            floodScore++;
        }
    }
    
    private void quitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBTNActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit? You will lose all your progress.", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new MainProgramGUI(loggedInUser, users).setVisible(true);
            dispose();
            // If NO, do nothing
        }
    }//GEN-LAST:event_quitBTNActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        // Calculate grades
        grade();
        
        // reading data from file to array list
        users = AccountManager.load();

        // update user's fire score
        loggedInUser.setFloodScore(Integer.toString(floodScore));

        //update in the array list by replacing old account with updated account
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUsername().equals(loggedInUser.getUsername())) {
                users.set(i, loggedInUser); // replace with updated account
                break;
            }
        }

        // Write array list back to file
        AccountManager.writeToFile(users);

        // Display test score when going back to main program
        MainProgramGUI m = new MainProgramGUI(loggedInUser, users);
        m.displayFloodScore();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_submitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Account a = new Account();
        ArrayList<Account> users = new ArrayList<>();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FloodQuizGUI(a, users).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupQ1;
    private javax.swing.ButtonGroup buttonGroupQ4;
    private javax.swing.ButtonGroup buttonGroupQ5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel q1LBL;
    private javax.swing.JPanel q1PN;
    private javax.swing.JRadioButton q1aRBTN;
    private javax.swing.JRadioButton q1bRBTN;
    private javax.swing.JRadioButton q1cRBTN;
    private javax.swing.JLabel q2LBL;
    private javax.swing.JPanel q2PN;
    private javax.swing.JCheckBox q2aCB;
    private javax.swing.JCheckBox q2bCB;
    private javax.swing.JLabel q3LBL;
    private javax.swing.JPanel q3PN;
    private javax.swing.JCheckBox q3aCB;
    private javax.swing.JCheckBox q3bCB;
    private javax.swing.JCheckBox q3cCB;
    private javax.swing.JCheckBox q3dCB;
    private javax.swing.JCheckBox q3eCB;
    private javax.swing.JCheckBox q3fCB;
    private javax.swing.JLabel q4LBL;
    private javax.swing.JPanel q4PN;
    private javax.swing.JRadioButton q4aRBTN;
    private javax.swing.JRadioButton q4bRBTN;
    private javax.swing.JRadioButton q4cRBTN;
    private javax.swing.JLabel q5LBL;
    private javax.swing.JPanel q5PN;
    private javax.swing.JRadioButton q5aRBTN;
    private javax.swing.JRadioButton q5bRBTN;
    private javax.swing.JRadioButton q5cRBTN;
    private javax.swing.JButton quitBTN;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
