/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhungLearnSafe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hong-nhung-nguyen
 */
public class MainProgramGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainProgramGUI.class.getName());
//    private int fireScore, floodScore;
    private Account loggedInUser;
    private ArrayList<Account> users;
    
    // add a setter for logged in user
    public Account getLoggedInUser() {
        return loggedInUser;
    }
    
    public ArrayList<Account> getUsers() {
        return users;
    }


    /**
     * Creates new form MainProgram
     * 
     * @param a
     * @param users
     */
    public MainProgramGUI(Account a, ArrayList<Account> users) {
        initComponents();
        this.loggedInUser = a;
        this.users = users;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizPN = new javax.swing.JPanel();
        firequizLBL = new javax.swing.JLabel();
        fireLessonBTN = new javax.swing.JButton();
        takeFireBTN = new javax.swing.JButton();
        overviewFireBTN = new javax.swing.JButton();
        floodquizLBL = new javax.swing.JLabel();
        overviewFloodBTN = new javax.swing.JButton();
        floodLessonBTN = new javax.swing.JButton();
        takeFloodBTN = new javax.swing.JButton();
        accountPN = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        certFireBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        accountManagerLBL = new javax.swing.JLabel();
        progressBTN = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();
        quitBTN = new javax.swing.JButton();
        deleteAccBTN = new javax.swing.JButton();
        guideIcon = new javax.swing.JLabel();
        guideBTN = new javax.swing.JButton();
        searchQuizPN = new javax.swing.JPanel();
        topicCBB = new javax.swing.JComboBox<>();
        topicLBL = new javax.swing.JLabel();
        progressLBL = new javax.swing.JLabel();
        progressCBB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizDisplayTA = new javax.swing.JTextArea();
        searchTitleLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quizPN.setBackground(new java.awt.Color(255, 102, 102));
        quizPN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        firequizLBL.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        firequizLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firequizLBL.setText("Fire Safety Quiz");

        fireLessonBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fireLessonBTN.setText("Lessons");
        fireLessonBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireLessonBTNActionPerformed(evt);
            }
        });

        takeFireBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        takeFireBTN.setText("Take Fire quiz");
        takeFireBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeFireBTNActionPerformed(evt);
            }
        });

        overviewFireBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        overviewFireBTN.setText("Overview");
        overviewFireBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewFireBTNActionPerformed(evt);
            }
        });

        floodquizLBL.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        floodquizLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floodquizLBL.setText("Flood Safety Quiz");

        overviewFloodBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        overviewFloodBTN.setText("Overview");
        overviewFloodBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewFloodBTNActionPerformed(evt);
            }
        });

        floodLessonBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        floodLessonBTN.setText("Lessons");
        floodLessonBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floodLessonBTNActionPerformed(evt);
            }
        });

        takeFloodBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        takeFloodBTN.setText("Take Flood quiz");
        takeFloodBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeFloodBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quizPNLayout = new javax.swing.GroupLayout(quizPN);
        quizPN.setLayout(quizPNLayout);
        quizPNLayout.setHorizontalGroup(
            quizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizPNLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(quizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firequizLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takeFloodBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(floodLessonBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewFloodBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fireLessonBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewFireBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takeFireBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floodquizLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        quizPNLayout.setVerticalGroup(
            quizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizPNLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(firequizLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewFireBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fireLessonBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(takeFireBTN)
                .addGap(18, 18, 18)
                .addComponent(floodquizLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewFloodBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(floodLessonBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(takeFloodBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountPN.setBackground(new java.awt.Color(204, 204, 204));

        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayTA.setRows(5);
        displayTA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(displayTA);

        certFireBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        certFireBTN.setText("Display certificate");
        certFireBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certFireBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteBTN.setText("Delete quiz result");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        accountManagerLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountManagerLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountManagerLBL.setText("ACCOUNT MANAGER");

        progressBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        progressBTN.setText("View quiz results");
        progressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressBTNActionPerformed(evt);
            }
        });

        logoutBTN.setBackground(new java.awt.Color(255, 102, 102));
        logoutBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        logoutBTN.setText("LOG OUT");
        logoutBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        quitBTN.setBackground(new java.awt.Color(51, 51, 51));
        quitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quitBTN.setForeground(new java.awt.Color(255, 255, 255));
        quitBTN.setText("EXIT");
        quitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBTNActionPerformed(evt);
            }
        });

        deleteAccBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteAccBTN.setForeground(new java.awt.Color(255, 0, 0));
        deleteAccBTN.setText("Delete account");
        deleteAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPNLayout = new javax.swing.GroupLayout(accountPN);
        accountPN.setLayout(accountPNLayout);
        accountPNLayout.setHorizontalGroup(
            accountPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPNLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(accountPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(accountPNLayout.createSequentialGroup()
                        .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountManagerLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(certFireBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(deleteAccBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        accountPNLayout.setVerticalGroup(
            accountPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPNLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(accountManagerLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certFireBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBTN)
                    .addComponent(quitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        guideIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        guideIcon.setText("jLabel2");

        guideBTN.setBackground(new java.awt.Color(242, 242, 242));
        guideBTN.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        guideBTN.setText("GUIDE");
        guideBTN.setBorder(null);
        guideBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guideBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        guideBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideBTNActionPerformed(evt);
            }
        });

        topicCBB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        topicCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural disaster", "Urban disaster", "Human-made disaster" }));
        topicCBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicCBBActionPerformed(evt);
            }
        });

        topicLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        topicLBL.setText("Topic");

        progressLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        progressLBL.setText("Your Progress");

        progressCBB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        progressCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passed", "Failed", "Not Taken" }));
        progressCBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressCBBActionPerformed(evt);
            }
        });

        quizDisplayTA.setColumns(20);
        quizDisplayTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quizDisplayTA.setRows(5);
        jScrollPane1.setViewportView(quizDisplayTA);

        searchTitleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchTitleLBL.setText("SEARCH FOR COURSES");

        javax.swing.GroupLayout searchQuizPNLayout = new javax.swing.GroupLayout(searchQuizPN);
        searchQuizPN.setLayout(searchQuizPNLayout);
        searchQuizPNLayout.setHorizontalGroup(
            searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchQuizPNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTitleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchQuizPNLayout.createSequentialGroup()
                        .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressLBL)
                            .addComponent(topicLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topicCBB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressCBB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        searchQuizPNLayout.setVerticalGroup(
            searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchQuizPNLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchQuizPNLayout.createSequentialGroup()
                        .addComponent(searchTitleLBL)
                        .addGap(18, 18, 18)
                        .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(topicLBL)
                            .addComponent(topicCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchQuizPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(progressCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressLBL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guideBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guideIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchQuizPN, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quizPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(accountPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(searchQuizPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guideIcon)
                    .addComponent(guideBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayFireScore(){
        displayTA.setLineWrap(true);
        displayTA.setText("Fire Safety Training: "+loggedInUser.getFireScore()+"/5"+"\n");
        if(loggedInUser.getFireScore().equals("5")){
            displayTA.append("Congratulations you passed! Select certificate to see your achievement");
        }else{
            int x = 5 - Integer.parseInt(loggedInUser.getFireScore());
            displayTA.append("You need "+x+" more points to get a certificate");
        }
    }
    
    public void displayFloodScore(){
        displayTA.setLineWrap(true);
        displayTA.setText("Flood Safety Training: "+loggedInUser.getFloodScore()+"\n");
        if(loggedInUser.getFloodScore().equals("5")){
            displayTA.append("Congratulations you passed! Select certificate to see your achievement");
        }else{
            int x = 5 - Integer.parseInt(loggedInUser.getFloodScore());
            displayTA.append("You need "+x+" more points to get a certificate");
        }
    }
    
    private void takeFireBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeFireBTNActionPerformed
        // TODO add your handling code here:
        FireQuizGUI fireGUI = new FireQuizGUI(loggedInUser, users);
        fireGUI.setVisible(true);
        this.setVisible(false); //hide main program
    }//GEN-LAST:event_takeFireBTNActionPerformed

    private void progressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressBTNActionPerformed
        // TODO add your handling code here:
        displayTA.setText(loggedInUser.viewProgress());
    }//GEN-LAST:event_progressBTNActionPerformed

    private void fireLessonBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireLessonBTNActionPerformed
        // TODO add your handling code here:
        new FireQuiz().showLesson();
    }//GEN-LAST:event_fireLessonBTNActionPerformed

    private void takeFloodBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeFloodBTNActionPerformed
        // TODO add your handling code here:
        FloodQuizGUI floodGUI = new FloodQuizGUI(loggedInUser, users);
        floodGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_takeFloodBTNActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new WelcomeGUI().setVisible(true);
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void floodLessonBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floodLessonBTNActionPerformed
        // TODO add your handling code here:
        new FloodQuiz().showLesson();
    }//GEN-LAST:event_floodLessonBTNActionPerformed

    private void overviewFireBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewFireBTNActionPerformed
        // TODO add your handling code here:
        new FireQuiz().summarize();
    }//GEN-LAST:event_overviewFireBTNActionPerformed

    private void overviewFloodBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewFloodBTNActionPerformed
        // TODO add your handling code here:
        new FloodQuiz().summarize();
    }//GEN-LAST:event_overviewFloodBTNActionPerformed

    private void certFireBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certFireBTNActionPerformed
        //check if user has any certificate
        if(!loggedInUser.getFireScore().equals("5") && !loggedInUser.getFloodScore().equals("5")){
            displayTA.setText("You have no certificate to display");
        
        //if user only has Fire certificate
        }else if(loggedInUser.getFireScore().equals("5") && !loggedInUser.getFloodScore().equals("5")){
            CertificateGUI cert = new CertificateGUI(loggedInUser, new FireQuiz());
            cert.setVisible(true);
            this.setVisible(false);
            
            // if user only has Flood certificate
        }else if(!loggedInUser.getFireScore().equals("5") && loggedInUser.getFloodScore().equals("5")){
            CertificateGUI cert = new CertificateGUI(loggedInUser, new FloodQuiz());
            cert.setVisible(true);
            this.setVisible(false);
        }else{
            String[] options = { "Fire", "Flood" };
            var selection = JOptionPane.showOptionDialog(null, "Select certificate you want to display", "Choose certificate", 
                                                             0, 2, null, options, options[0]);
            if (selection == 0) {   //options[0] = Fire
                CertificateGUI cert = new CertificateGUI(loggedInUser, new FireQuiz());
                cert.setVisible(true);
                this.setVisible(false);
            }
            if (selection == 1) {   //options[1] = Flood
                CertificateGUI cert = new CertificateGUI(loggedInUser, new FloodQuiz());
                cert.setVisible(true);
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_certFireBTNActionPerformed

    private void quitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        //ì user dóe not have any score to delete
        if (loggedInUser.getFireScore().equals("null") & loggedInUser.getFloodScore().equals("null")){
            displayTA.setText("You have no scores to delete");
            
        }else{
            //Ask user which quiz they want to delete score
            String[] options = { "Fire", "Flood" };
            var selection = JOptionPane.showOptionDialog(null, "Delete score", "Which quiz score do you want to delete?", 
                                                         0, 2, null, options, options[0]);
            if (selection == 0) {   //options[0] = Fire
                loggedInUser.setFireScore("null");
            }
            if (selection == 1) {   //options[1] = Flood
                loggedInUser.setFloodScore("null");
            }

            // update user's scores to array list
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i).getUsername().equals(loggedInUser.getUsername())) {
                    users.set(i, loggedInUser); // replace with updated account
                    break;
                }
            }

            //write arraylist to data file
            AccountManager.writeToFile(users);

            //display
            displayTA.setText("Your new scores are: \n");
            displayTA.append(loggedInUser.viewProgress());
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void guideBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideBTNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            Panel Quiz has 2 quizzes. Each quiz has three buttons:
                                            1. Overview: Show overall information about the quiz (topic, length)
                                            2. Lessons: Display relevant lessons
                                            3. Take quiz: Test your knowledge with 5 questions
                                            """);
        JOptionPane.showMessageDialog(null, """
                                            Panel Account Manager allows you to:
                                            - View quiz results
                                            - Display your certificate if you pass a quiz
                                            - Delete a specific quiz score
                                            - Delete your account
                                            """);
        JOptionPane.showMessageDialog(null, """
                                            Panel Search For Courses allows you to search for quizzes based on Topic or Your Progress.
                                            These criteria functions independently; you can't combine them.
                                            """);
    }//GEN-LAST:event_guideBTNActionPerformed

    private void topicCBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicCBBActionPerformed
        quizDisplayTA.setLineWrap(true);
        
        // make the output area blank
        quizDisplayTA.setText("");
        
        Quiz[] quizzes = {new FireQuiz(), new FloodQuiz()}; //create an array of all quizzes
        String topic = (String) topicCBB.getSelectedItem(); //topic is search term
        int count = 0;  //keep count of the quizzes that match search term
        
        for (int i = 0; i < quizzes.length; i++){
            if (quizzes[i].getTopic().equals(topic)){
                quizDisplayTA.append(quizzes[i].getTitle()+"\n");
                count++;
            }
        }
        
        // If no quizzes match search term
        if (count==0){
            quizDisplayTA.setText("No available courses for topic "+topic);
        }
    }//GEN-LAST:event_topicCBBActionPerformed

    private void progressCBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressCBBActionPerformed
        // TODO add your handling code here:
        quizDisplayTA.setLineWrap(true);
        
        // make the output area blank
        quizDisplayTA.setText("");
        
        String progress = (String) progressCBB.getSelectedItem(); //topic is search term
        
        if (progress.equals("Passed")){
            boolean firepass = false;
            boolean floodpass = false;
            if("5".equals(loggedInUser.getFireScore())){
                quizDisplayTA.append(new FireQuiz().getTitle()+"\n");
                firepass = true;
            }
            if("5".equals(loggedInUser.getFloodScore())){
                quizDisplayTA.append(new FloodQuiz().getTitle()+"\n");
                floodpass = true;
            }
            if(firepass == false && floodpass == false){
                quizDisplayTA.setText("You have not passed any quiz");
            }
            
        } else if (progress.equals("Failed")){
            
            boolean firefail = false;
            boolean floodfail = false;
            
            //you fail if score is not 5 AND score is not null
            if(!loggedInUser.getFireScore().equals("null") && !"5".equals(loggedInUser.getFireScore())){
                quizDisplayTA.append(new FireQuiz().getTitle()+"\n");
                firefail = true;
            }
            
            if(!loggedInUser.getFloodScore().equals("null") && !"5".equals(loggedInUser.getFloodScore())){
                quizDisplayTA.append(new FloodQuiz().getTitle()+"\n");
                firefail = true;
            }
            
            // if both flags are false, user has not failed any quiz
            if(firefail == false && floodfail == false){
                quizDisplayTA.setText("You have not failed any quiz");
            }
            
        } else if (progress.equals("Not Taken")){
            // quiz scores are "null" by default if user didn't take the quiz
            if (loggedInUser.getFireScore().equals("null")){
                quizDisplayTA.append(new FireQuiz().getTitle()+"\n");
            }
            if (loggedInUser.getFloodScore().equals("null")){
                quizDisplayTA.append(new FloodQuiz().getTitle()+"\n");
            }
            
            //when user starts a quiz, his scores are no longer of type 'null'
            if (!loggedInUser.getFireScore().equals("null") & !loggedInUser.getFloodScore().equals("null")){
                quizDisplayTA.setText("You took all quizzes");
            }
        }
    }//GEN-LAST:event_progressCBBActionPerformed

    private void deleteAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccBTNActionPerformed
        String password = JOptionPane.showInputDialog(null, "Enter your password to delete your account");
        if (password.equals(loggedInUser.getPassword())){
            users.remove(loggedInUser);
            
            // update data file
            AccountManager.writeToFile(users);
        }
        
        // exit the app and display message
        System.out.println("Account deleted successfully");
        System.exit(0);
        
    }//GEN-LAST:event_deleteAccBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Account a = new Account();
        ArrayList<Account> users = new ArrayList<>();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainProgramGUI(a, users).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountManagerLBL;
    private javax.swing.JPanel accountPN;
    private javax.swing.JButton certFireBTN;
    private javax.swing.JButton deleteAccBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton fireLessonBTN;
    private javax.swing.JLabel firequizLBL;
    private javax.swing.JButton floodLessonBTN;
    private javax.swing.JLabel floodquizLBL;
    private javax.swing.JButton guideBTN;
    private javax.swing.JLabel guideIcon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton overviewFireBTN;
    private javax.swing.JButton overviewFloodBTN;
    private javax.swing.JButton progressBTN;
    private javax.swing.JComboBox<String> progressCBB;
    private javax.swing.JLabel progressLBL;
    private javax.swing.JButton quitBTN;
    private javax.swing.JTextArea quizDisplayTA;
    private javax.swing.JPanel quizPN;
    private javax.swing.JPanel searchQuizPN;
    private javax.swing.JLabel searchTitleLBL;
    private javax.swing.JButton takeFireBTN;
    private javax.swing.JButton takeFloodBTN;
    private javax.swing.JComboBox<String> topicCBB;
    private javax.swing.JLabel topicLBL;
    // End of variables declaration//GEN-END:variables
}
