/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhungLearnSafe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author surface pro 6
 */
public class WelcomeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomeGUI.class.getName());

    private ArrayList<Account> users;

    /**
     * Creates new form WelcomeGUI
     */
    public WelcomeGUI() {
        initComponents();
        users = AccountManager.load();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionBTNGR = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        text1LBL = new javax.swing.JLabel();
        signInBTN = new javax.swing.JRadioButton();
        usernameLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordF = new javax.swing.JPasswordField();
        continueBTN = new javax.swing.JButton();
        text2LBL = new javax.swing.JLabel();
        backtoMenuBTN = new javax.swing.JButton();
        newAccBTN = new javax.swing.JRadioButton();
        displayLBL = new javax.swing.JLabel();
        titleIcon = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        text1LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text1LBL.setText("In this section, you will learn what actions to take when a fire or a flood");

        optionBTNGR.add(signInBTN);
        signInBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signInBTN.setText("Sign in");
        signInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBTNActionPerformed(evt);
            }
        });

        usernameLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLBL.setText("Username:");

        passwordLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLBL.setText("Password:");

        continueBTN.setBackground(new java.awt.Color(255, 102, 51));
        continueBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        continueBTN.setForeground(new java.awt.Color(255, 255, 255));
        continueBTN.setText("Continue");
        continueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBTNActionPerformed(evt);
            }
        });

        text2LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text2LBL.setText("occurs. You will receive a certificate once you score 5/5 on a quiz.");

        backtoMenuBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backtoMenuBTN.setText("Back to Menu");
        backtoMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMenuBTNActionPerformed(evt);
            }
        });

        optionBTNGR.add(newAccBTN);
        newAccBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newAccBTN.setText("Create a new account");

        displayLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayLBL.setForeground(new java.awt.Color(255, 51, 51));
        displayLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        titleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/idea.png"))); // NOI18N
        titleIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 102, 0));
        titleLBL.setText("Welcome to LearnSafe!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(titleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(text2LBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newAccBTN)
                            .addComponent(signInBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backtoMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(usernameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(continueBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(passwordLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(text1LBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(titleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(text1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2LBL)
                .addGap(11, 11, 11)
                .addComponent(displayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newAccBTN)
                        .addComponent(usernameLBL))
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signInBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLBL)
                            .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(continueBTN)
                    .addComponent(backtoMenuBTN))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void continueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBTNActionPerformed
        //Check if user has chosen either "sign in" or "Create new account"
        
        if(newAccBTN.isSelected()){
            //Take input from user
            String username = usernameTF.getText();
            String password = passwordF.getText();
            
            // check if username already exists using a static method
            if (AccountManager.usernameExists(users, username)) {   //if usernameExists == true
                displayLBL.setText("Username already exists");
            } else {
                // if username is valid, check if user leaves anything blank
                if (username.isBlank() || password.isBlank()){
                    displayLBL.setText("Missing username or password");
                } else {
                    Account tempA = new Account(username, password);
                    users.add(tempA);
                   
                    // write array list to data file
                    AccountManager.writeToFile(users);
                   
                    JOptionPane.showMessageDialog(null, "Account created successfully! Please log in to continue");
                }
            }
            
        } else if(signInBTN.isSelected()){
            String username = usernameTF.getText();
            String password = passwordF.getText();
            
            if (username.isBlank() || password.isBlank()){
                displayLBL.setText("Missing username or password");
                
            }else{
                // Use a static method to check if credentials are correct. The method return Account object or null.
                Account loggedInUser = AccountManager.authenticate(users, username, password);
                if (loggedInUser == null){
                    displayLBL.setText("Invalid username or password");
                }else{
                    MainProgramGUI m = new MainProgramGUI(loggedInUser, users);   //pass account to main program
                    m.setVisible(true);
                    dispose();
                }
            }
            
        }else{
            displayLBL.setText("Please select an option");
        }
    }//GEN-LAST:event_continueBTNActionPerformed

    private void signInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signInBTNActionPerformed

    private void backtoMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMenuBTNActionPerformed
        // This button takes user back to main menu of the application after we combine 3 packages
    }//GEN-LAST:event_backtoMenuBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WelcomeGUI().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMenuBTN;
    private javax.swing.JButton continueBTN;
    private javax.swing.JLabel displayLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton newAccBTN;
    private javax.swing.ButtonGroup optionBTNGR;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JRadioButton signInBTN;
    private javax.swing.JLabel text1LBL;
    private javax.swing.JLabel text2LBL;
    private javax.swing.JLabel titleIcon;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel usernameLBL;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
